//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveContent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public string C_idBaiViet { get; set; }
        public string C_idTheLoai { get; set; }
        public string C_idUserDang { get; set; }
        public string TieuDe { get; set; }
        public string TomTatNoiDung { get; set; }
        public byte[] AnhBia { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> SoLanXem { get; set; }
        public Nullable<bool> TrangThaiBaiViet { get; set; }
    
        public virtual TheLoai TheLoai { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}
