//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveContent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinhLuan()
        {
            this.BinhLuan1 = new HashSet<BinhLuan>();
        }
    
        public string C_idBinhLuan { get; set; }
        public string C_idUserDoc { get; set; }
        public Nullable<System.DateTime> ThoiDiemBinhLuan { get; set; }
        public string C_idBaiViet { get; set; }
        public string NoiDung { get; set; }
        public string C_idBinhLuanGoc { get; set; }
        public Nullable<int> CapBac { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan1 { get; set; }
        public virtual BinhLuan BinhLuan2 { get; set; }
        public virtual User User { get; set; }
    }
}
