//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveContent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuNapTien
    {
        public string C_idLichSuNapTien { get; set; }
        public string C_idUserDang { get; set; }
        public string C_idUserDoc { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
        public Nullable<double> MenhGia { get; set; }
        public Nullable<int> ThoiHan { get; set; }
        public string Seri { get; set; }
        public string MaSMS { get; set; }
    
        public virtual User User { get; set; }
    }
}
